autolabeler:
  - label: 'chore'
    branch:
      - '/chores{0,1}\/.*/'
    title:
      - '^chore.*'
    files:
      - '.github/**'
  - label: 'documentation'
    files:
      - 'README.md'
    branch:
      - '/docs{0,1}\/.*/'
    title:
      - '^doc.*'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/(bug|bugfix|fix|hotfix)\/.*/'
    title:
      - '^(bug|bugfix|fix|hotfix).*'
  - label: 'enhancement'
    branch:
      - '/(feat|feature)\/.*/'
      - '/enhancement\/.*/'
    title:
      - '^(feat|feature).*'
      - '^enhancement.*'
    body:
      - '/JIRA-[0-9]{1,4}/'
  - label: 'refactor'
    branch:
      - '/refactor\/.*/'
    title:
      - '^refactor/*'

name-template: '$RESOLVED_VERSION'

template: |
  $CHANGES
category-template: '## $TITLE'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'feat'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'refactor'
      - 'chore'
  - title: '📝 Document'
    labels:
      - 'docs'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

sort-by: 'title'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

exclude-labels:
  - 'skip_changelog'
