autolabeler:
  - label: 'chore'
    branch:
      - '/chores{0,1}\/.*/'
    title:
      - '/^chore.*/i'
    files:
      - '.github/**'
  - label: 'documentation'
    files:
      - 'README.md'
    branch:
      - '/docs{0,1}\/.*/'
    title:
      - '/^doc.*/i'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/(bug|bugfix|fix|hotfix)\/.*/'
    title:
      - '/^(bug|bugfix|fix|hotfix).*/i'
  - label: 'feature'
    branch:
      - '/(feat|feature)\/.*/'
    title:
      - '/^(feat|feature).*/i'
  - label: 'enhancement'
    branch:
      - '/enhancement\/.*/'
    title:
      - '/^enhancement.*/i'
  - label: 'refactor'
    branch:
      - '/refactor\/.*/'
    title:
      - '/^refactor.*/i'

name-template: '$RESOLVED_VERSION'

template: |
  $CHANGES
category-template: '## $TITLE'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'refactor'
      - 'chore'
  - title: '📝 Document'
    labels:
      - 'documentation'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

sort-by: 'title'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

exclude-labels:
  - 'skip_changelog'
