#!/bin/sh

# stash any unstaged changes
git stash -q --keep-index

# run the tests with the gradle wrapper
./gradlew goJF
./gradlew clean build

# store the last exit code in a variable
RESULT=$?

# unstash the unstashed changes
git stash pop -q

# return the './gradlew build' exit code
exit $RESULT